language: generic
before_install:
  - sudo apt update
  - sudo apt install -y python-docutils texlive pdftk
  - git clone --branch = ucd-mae-hip --depth 1 https://github.com/moorepants/resume.git
script:
  - make -C 2018/ucd-mae-hip RESUMELOC="resume"
